package aoc.year2025.day07

import aoc.common.Matrix

val example = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
""".trimIndent().lines()

enum class Tile(val char: Char) {
    START('S'),
    SPACE('.'),
    BEAM('|'),
    SPLITTER('^');

    override fun toString() = char.toString()

    companion object {
        fun parse(char: Char): Tile = entries.first { it.char == char }
    }
}

fun parseMatrix(input: List<String>) = Matrix.parse(input) { Tile.parse(it) }
